
name: main-actions
run-name: ${{ github.actor }} is running GitHub Actions
on:
  push:
    branches: [ "feature*" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v3
    - name: Step 1
      run: echo "Step 1"
    - name: Step 2
      run: echo "Step 2"