
name: main-actions
run-name: ${{ github.actor }} is running GitHub Actions
on:
  push:
    branches: [ "feature*" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    environment: my-repo
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
        
    - uses: actions/checkout@v3
    - name: Copy .env
      run: echo {{ env.DB_HOST }}
      # run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # - uses: php-actions/composer@v6
    # - name: Install Dependencies
    #   run: echo "Step install dependancies"
    # - name: Generate key
    #   run: php artisan key:generate
    # - name: Directory Permissions
    #   run: chmod -R 777 storage bootstrap/cache
    # - name: Run API Test
    #   run: php artisan test